### ISSUE TITLE
Unlimited Money Glitch?

### ISSUE THREAD

**Issue by Byolock** [KillerDJLang/Saria#1]
For me Saria (LV1) sells the "Mystery Ranch NICE COMM 3 BVS frame System" for 129.999 Roubles. This Item can be sold for 217.000 Roubles to Ragman. I didn't try it but this seems to me like a source for unlimited money.

Im not aware of any other mods i have which could alter the selling price for this item.

**Comment by KillerDJLang** [comment]
Thank you, I'll look into it.
I'll double check the rest while I'm at it too

**Comment by KillerDJLang** [comment]
Just rebalanced all pricing, thanks for the report
